import { Candidate } from "@/types/candidate";

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Sneha Reddy",
    email: "sneha@gmail.com",
    role: "Backend Developer",
    source: "Gmail",
    match: 94,
    status: "Shortlisted",
    appliedDate: "Today",
  },
  {
    id: "2",
    name: "Rahul Sharma",
    email: "rahul@gmail.com",
    role: "Frontend Developer",
    source: "Referral",
    match: 91,
    status: "Review",
    appliedDate: "Today",
  },
  {
    id: "3",
    name: "Priya Patel",
    email: "priya@gmail.com",
    role: "Full Stack Developer",
    source: "LinkedIn",
    match: 88,
    status: "New",
    appliedDate: "Yesterday",
  },
  {
    id: "4",
    name: "Arjun Kumar",
    email: "arjun@gmail.com",
    role: "Backend Developer",
    source: "Gmail",
    match: 85,
    status: "Review",
    appliedDate: "Yesterday",
  },
  {
    id: "5",
    name: "Akash Verma",
    email: "akash@gmail.com",
    role: "Node Developer",
    source: "Referral",
    match: 82,
    status: "New",
    appliedDate: "2 days ago",
  },
  {
    id: "6",
    name: "Meera Nair",
    email: "meera@gmail.com",
    role: "React Developer",
    source: "Gmail",
    match: 80,
    status: "Review",
    appliedDate: "2 days ago",
  },
  {
    id: "7",
    name: "John Mathew",
    email: "john@gmail.com",
    role: "Software Engineer",
    source: "LinkedIn",
    match: 79,
    status: "Rejected",
    appliedDate: "3 days ago",
  },
  {
    id: "8",
    name: "Anjali Singh",
    email: "anjali@gmail.com",
    role: "Backend Developer",
    source: "Gmail",
    match: 95,
    status: "Shortlisted",
    appliedDate: "Today",
  },
  {
    id: "9",
    name: "Rohit Gupta",
    email: "rohit@gmail.com",
    role: "Node.js Developer",
    source: "Referral",
    match: 90,
    status: "Review",
    appliedDate: "Today",
  },
  {
    id: "10",
    name: "Keerthi Rao",
    email: "keerthi@gmail.com",
    role: "React Developer",
    source: "Gmail",
    match: 86,
    status: "New",
    appliedDate: "Yesterday",
  },
];